### ISSUE TITLE
the library doesn't work with javafx date picker

### ISSUE THREAD

**Issue by Xerophytex** [andegna/EthiopianChronology#3]
hey guys first of all i would like to say this library is the closest i have gotten to work for my project. the problem is i can't get it to work on javafx date picker. when i try to use your api like this

    date.setChronology(EthiopianChronology.INSTANCE);
   date.setUserData(EthiopianChronology.INSTANCE);
         
         date.chronologyProperty().setValue(EthiopianChronology.INSTANCE);
     date.setValue(LocalDate.now());
         
it gives me an error message  below.

at sun.util.locale.provider.CalendarDataUtility.normalizeCalendarType(CalendarDataUtility.java:107)
	at sun.util.locale.provider.CalendarDataUtility.retrieveJavaTimeFieldValueName(CalendarDataUtility.java:76)
	at java.time.format.DateTimeTextProvider.getText(DateTimeTextProvider.java:198)
	at java.time.format.DateTimeFormatterBuilder$TextPrinterParser.format(DateTimeFormatterBuilder.java:3101)
	at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2179)
	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1746)
	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)
	at com.jfoenix.skins.JFXDatePickerContent.formatMonth(JFXDatePickerContent.java:720)
	at com.jfoenix.skins.JFXDatePickerContent.updateMonthYearPane(JFXDatePickerContent.java:708)
	at com.jfoenix.skins.JFXDatePickerContent.updateValues(JFXDatePickerContent.java:611)
	at com.jfoenix.skins.JFXDatePickerContent.refresh(JFXDatePickerContent.java:590)

any help would be appreciated thanks

**Comment by SamAsEnd** [comment]
Damn, i have not used this library in the last **five years** and it wasn't tested on JavaFx ¯\_(ツ)_/¯

Sorry bro, i don't i can help you
